# Generated by Django 4.1.5 on 2023-01-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название Карточки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание Карточки')),
                ('service_price', models.PositiveIntegerField(verbose_name='%  за обслуживание')),
                ('delivery_price', models.PositiveIntegerField(verbose_name='Цена за доставку')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(choices=[(1, 'Service'), (2, 'Delivery'), (3, 'Pickup')], default=1, verbose_name='Тип Заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в ')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='обнавлен в ')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Общая сумма заказа')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена продукта')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.establishment')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество продукта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.product')),
            ],
            options={
                'verbose_name': 'Единица Заказа',
                'verbose_name_plural': 'Единицы Заказа',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=13, verbose_name='Номер Телефона')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание для Доставщика')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='order.order')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
